 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.1.42:8000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 326-687-733
Traceback (most recent call last):
  File "/Users/nadeem/Documents/Moiz/Learning Dev/Next/tutoring-app/backend/app.py", line 32, in <module>
    app.run(debug=True, host='0.0.0.0', port=8000)
  File "/Users/nadeem/Documents/Moiz/Learning Dev/Next/tutoring-app/backend/venv/lib/python3.12/site-packages/flask/app.py", line 889, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/nadeem/Documents/Moiz/Learning Dev/Next/tutoring-app/backend/venv/lib/python3.12/site-packages/werkzeug/serving.py", line 1115, in run_simple
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
OSError: [Errno 9] Bad file descriptor

Current thread 0x00000001f3bbf840 (most recent call first):
  <no Python frame>
    run_with_reloader(
  File "/Users/nadeem/Documents/Moiz/Learning Dev/Next/tutoring-app/backend/venv/lib/python3.12/site-packages/werkzeug/_reloader.py", line 459, in run_with_reloader
    ensure_echo_on()
  File "/Users/nadeem/Documents/Moiz/Learning Dev/Next/tutoring-app/backend/venv/lib/python3.12/site-packages/werkzeug/_reloader.py", line 439, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (4, 'Interrupted system call')
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py:123: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
  warnings.warn('resource_tracker: process died unexpectedly, '
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
OSError: [Errno 9] Bad file descriptor

Current thread 0x00000001f3bbf840 (most recent call first):
  <no Python frame>
